### ISSUE TITLE
[discussion] 6월 6일 오프라인 회의 정리

### ISSUE THREAD

**Issue by annapo99** [depromeet/gather-move-iOS#80]
# 논의사항 
결정된 사항을 정리합니다.

## Folder 네이밍 한 뎁스 낮추는 것으로 결정
Tuist로 패키지 및 폴더를 강제하므로, 폴더 이름에서 중복을 제거하는 것으로 합니다.
```swift
Feature/FeatureOnboarding/FeatureOnboardingHome
->
Feature/Onboarding/Home
```

## View는 인터페이스로 결정
오래된 이슈였는데, 결국 View와 Store가 모두 Interface에 있어야 View 타입을 재사용할 수 있다는 결정이 있었습니다.
아래의 이슈를 해결하고자 하기 위함입니다. 같은 레이어의 모듈간 Implements를 서로 몰라야하고 Interface로만 소통해야 함입니다.

또한 store의 구현부를 빼낸 것처럼 할수 있었지만, 그럴 필요가 없다는 결론을 내렸습니다. View는 껍데기일 뿐이고, Store가 핵심 비즈니스 로직을 담당하기 때문에 이부분만 빼내면 된다는 판단입니다.

즉 FeatureHome과 FeatureProfile은 Interface로 소통하고, Feature에서 FeatureHome과 FeatureProfile을 컴포지션 합니다.

```swift

// FeatureHome에서 FeatureProfile이 필요한 상항에서 다음과 같이 해결합니다.
// Feature
import FeatureProfile
import FeatureProfileInterface
import FeatureHome
import FeatureHomeInterface

let makeOtherProfileView: (...)  -> OtherProfileView = { ... in
    return OtherProfileView(store: ...)
}

HomeRootView(..., makeOtherProfileView: makeOtherProfileView)

// FeatureHome
struct HomeRootView: View {
     let makeOtherProfileView: (...) -> OtherProfileView

     public init(..., makeOtherProfileView:  @escaping (...) -> OtherProfileView) {
          ...
          self.makeOtherProfileView = makeOtherProfileView
    }
}
```

## Cell을 DesignSystem에 포함되고, Store와 View를 한쌍(또는 많이)로 갖는 것으로 결정
Cell은 재사용을 위한 struct임이 분명하고, CellView와 CellStore로 나누어서 파일을 관리합니다. Cell이 상태를 갖게 설계하는 것을 피하며, 반드시 부모에게 내려받는 상태로 관리하는 것으로 하는 것을 강제합니다. 

## DesignSystem의 Components에 해당하는 View는 Store를 갖지 않는 것으로 결정
Button, TextField 등 으로 사용되는 공통 컴포넌트는 Binding 키워드를 통해 관리합니다.

 물론 상태는 부모에서 관리합니다.

**Comment by parkhj0423** [comment]
+ 추가 App의 Root에서 온보딩과 탭뷰를 분기하여 처리했고, Feature의 Root에서는 탭뷰를 구성하는 피쳐들을 가지고 있는 식으로 작성했습니다.

**Comment by annapo99** [comment]
이슈를 닫습니다.
